COUNT=$1
TAGS=$2
EOS_DIR_TAGS=$3
EOS_CS2C2_DIR_TAGS=$4
EOS_PER_DIR=$5

add-covariates $COUNT $TAGS $EOS_DIR_TAGS $EOS_CS2C2_DIR_TAGS $EOS_PER_DIR

add_delta_r.sh $COUNT $TAGS $EOS_DIR_TAGS $EOS_CS2C2_DIR_TAGS $EOS_PER_DIR





