#!/bin/bash

### make plots of nuclear parameters alongside EoS params and macroscopic observables


#-------------------------------------------------

NUM_POINTS=101
MAX_NUM_SAMPLES=100000



#---

declare -A TAGMAP
TAGMAP["sp"]="SPECTRAL"
TAGMAP["pp"]="PIECEWISE"
TAGMAP["cs"]="SPEED-OF-SOUND"

PARTAGS="cs sp pp"
for TAG in $PARTAGS
do

    echo "----------"
    echo "processing $TAG"
    echo "----------"
    # Again this is silly but will make things easier
    # This script should only be called by condor, and in particular with
    # the submit file that requires you to be in the correct directory anways
    # this shouldn't cause big problems for now
    cd ../..
    MAIN_DIR=$(pwd)
    cd Utils/Plotting

    PARTAG=${TAGMAP[$TAG]}
    NP_SAMPS=$MAIN_DIR"/corrected_np_all_post.csv"
    

    NPPRIOR="PRIOR(NONPARAMETRIC)"
    PSR="PSR"
    PSRGW="PSR+GW"
    NP="NONPARAMETRIC"

    # These things will have to change for each parametric instance
    PAR_SAMPS=$MAIN_DIR"/corrected_${TAG}_all_post.csv"
    PARPRIOR="PRIOR(${PARTAG})"
    PAR="$PARTAG"
    
    
    DEFAULT_COLOR_SCHEME="--color $NP deepskyblue ""--color $NPPRIOR blue "" --color $PAR orange  ""--color  $PARPRIOR darkgoldenrod"
    DEFAULT_VARIABLE_RANGES="--column-range Mmax 1.8 3.0"
 
    kde-corner-samples \
        Mmax 'R(M=1.4)' 'R(M=2.0)' 'Lambda(M=1.4)' 'Lambda(M=2.0)' 'pressurec2(baryon_density=5.6e+14)' 'pressurec2(baryon_density=1.68e+15)' \
        --column-label Mmax '$M_\mathrm{max}\ [M_\odot]$' \
        --column-range Mmax 1.90 3.0 \
        --column-bandwidth Mmax 0.04 \
        --column-label 'R(M=1.4)' '$R_{1.4}\ [\mathrm{km}]$' \
        --column-range 'R(M=1.4)' 8.5 16.0 \
        --column-bandwidth 'R(M=1.4)' 0.20 \
        --column-label 'R(M=2.0)' '$R_{2.0}\ [\mathrm{km}]$' \
        --column-range 'R(M=2.0)' 9.1 14.9 \
        --column-bandwidth 'R(M=2.0)' 0.20 \
        --column-label 'Lambda(M=1.4)' '$\Lambda_{1.4}$' \
        --column-range 'Lambda(M=1.4)' 1.0 999.0 \
        --column-bandwidth 'Lambda(M=1.4)' 40 \
        --column-label 'Lambda(M=2.0)' '$\Lambda_{2.0}$' \
        --column-range 'Lambda(M=2.0)' 1.0 150.0 \
        --column-bandwidth 'Lambda(M=2.0)' 5 \
        --logcolumn 'pressurec2(baryon_density=5.6e+14)' \
        --column-label 'pressurec2(baryon_density=5.6e+14)' '$\log_{10}\left(p_{2.0}/c^2\ [\mathrm{g}/\mathrm{cm}^3]\right)$' \
        --column-range 'pressurec2(baryon_density=5.6e+14)' 12.9 14.2 \
        --column-bandwidth 'pressurec2(baryon_density=5.6e+14)' 0.10 \
        --column-multiplier "pressurec2(baryon_density=5.6e+14)" .43429\
        --logcolumn 'pressurec2(baryon_density=1.68e+15)' \
        --column-label 'pressurec2(baryon_density=1.68e+15)' '$\log_{10}\left(p_{6.0}/c^2\ [\mathrm{g}/\mathrm{cm}^3]\right)$' \
        --column-range 'pressurec2(baryon_density=1.68e+15)' 14.2 15.5 \
        --column-bandwidth 'pressurec2(baryon_density=1.68e+15)' 0.10 \
        --column-multiplier "pressurec2(baryon_density=1.68e+15)" .43429\
        -s $NP $NP_SAMPS \
        --weight-column $NP logweight_total\
        --weight-column-is-log $NP logweight_total\
        -s $NPPRIOR $NP_SAMPS\
        -s $PARPRIOR $PAR_SAMPS\
        -s $PAR $PAR_SAMPS \
        $DEFAULT_COLOR_SCHEME\
        --linestyle $NPPRIOR "dashdot"\
        --linestyle $PARPRIOR "dashdot"\
        --weight-column $PAR logweight_total\
        --weight-column-is-log $PAR logweight_total\
        --output-dir $MAIN_DIR \
        --tag "$TAG-comparison" \
        --num-proc 16 \
        --num-points $NUM_POINTS \
        --level 0.9 \
        --legend \
        --grid \
        --rotate-xticklabels 90 \
        --figwidth 11.8 \
        --figheight 11.8 \
        --Verbose \
        --no-scatter \
        --Verbose 
        
done
