#!/bin/bash

### make plots of nuclear parameters alongside EoS params and macroscopic observables

# E_beta,E_PNM,x,S0,L,Ksym,eps_total,eps_electron,mu_electron,EoS,Mmax,numbranches,logweight_NICER,logweight_GW170817,logweight_GW190425,logweight_J0348,logweight_J0740,logweight_J1614,pressurec2(baryon_density=1.4e+14),pressurec2(baryon_density=2.8e+14),pressurec2(baryon_density=4.2e+14),pressurec2(baryon_density=5.6e+14),pressurec2(baryon_density=8.4e+14),pressurec2(baryon_density=1.12e+15),energy_densityc2(baryon_density=1.4e+14),energy_densityc2(baryon_density=2.8e+14),energy_densityc2(baryon_density=4.2e+14),energy_densityc2(baryon_density=5.6e+14),energy_densityc2(baryon_density=8.4e+14),energy_densityc2(baryon_density=1.12e+15),R(M=1.4),R(M=1.6),Lambda(M=1.4),Lambda(M=1.6)

#-------------------------------------------------

NUM_POINTS=101
MAX_NUM_SAMPLES=100000


NPPRIOR="PRIOR(NONPARAMETRIC)"
SPPRIOR="SPECTRAL(PARAMETRIC)"
PSR="PSR"
PSRGW="PSR+GW"
NP="NONPARAMETRIC"
SP="SPECTRAL"
NP_REW="NONPARAMETRIC(REWEIGHTED-M)"
SP_REW="SPECTRAL(REWEIGHTED-M)"

#---

# plot different posteriors for the same set of prior draws
# this is irrelevant, at this point all of the
# data is already collated, just need one tag value
TAGS="/home/philippe.landry/nseos/eos/gp/mrgagn/"

for TAG in $TAGS
do

    echo "----------"
    echo "processing $TAG"
    echo "----------"
    # Again this is silly but will make things easier
    # This script should only be called by condor, and in particular with
    # the submit file that requires you to be in the correct directory anways
    # this shouldn't cause big problems for now
  
    cd ../..
    MAIN_DIR=$(pwd)
    cd Utils/Plotting

    THIS_TAG="compare_r1p4_reweighting_sp_np"
    
    SAMPS1=$MAIN_DIR"/corrected_np_all_post.csv"
    SAMPS2=$MAIN_DIR"/corrected_sp_all_post.csv"

    IN1="$NP"
    IN2="$SP"
    OUT1="$NP_REW"
    OUT2="$SP_REW"

    NEW_WEIGHT="Mmax_prior_kde"
    
    DEFAULT_COLOR_SCHEME="--color $OUT1 deepskyblue ""--color $IN2 blue "" --color $OUT2 magenta ""--color  $IN2 red"
    
    SPECIFIC_COLOR_SCHEME="--color $IN1 deepskyblue ""--color $OUT1 teal "" --color $IN2 magenta ""--color  $OUT2 orange "

    COLOR_SCHEME="$SPECIFIC_COLOR_SCHEME"


    # This would give prior1, posterior1, prior2, posterior2
    DEFAULT_WEIGHT_ARGS="--weight-column $OUT1 logweight_total --weight-column-is-log $OUT1 logweight_total --weight-column $OUT2 logweight_total --weight-column-is-log $OUT2 logweight_total"
    
    EXTRA_WEIGHT_ARGS="--weight-column $IN1 logweight_total --weight-column-is-log $IN1 logweight_total --weight-column $IN2 logweight_total --weight-column-is-log $IN2 logweight_total --weight-column $OUT1 $NEW_WEIGHT --weight-column-is-log $OUT1 $NEW_WEIGHT --invert-weight-column $OUT1 $NEW_WEIGHT --weight-column $OUT2 $NEW_WEIGHT --weight-column-is-log $OUT2 $NEW_WEIGHT --invert-weight-column $OUT2 $NEW_WEIGHT"
    
    kde-corner-samples \
        Mmax 'R(M=1.4)' 'R(M=2.0)' 'Lambda(M=1.4)' 'Lambda(M=2.0)' 'pressurec2(baryon_density=5.6e+14)' 'pressurec2(baryon_density=1.68e+15)' \
        --column-label Mmax '$M_\mathrm{max}\ [M_\odot]$' \
        --column-range Mmax 1.90 3.0 \
        --column-bandwidth Mmax 0.04 \
        --column-label 'R(M=1.4)' '$R_{1.4}\ [\mathrm{km}]$' \
        --column-range 'R(M=1.4)' 8.5 16.0 \
        --column-bandwidth 'R(M=1.4)' 0.20 \
        --column-label 'R(M=2.0)' '$R_{2.0}\ [\mathrm{km}]$' \
        --column-range 'R(M=2.0)' 9.1 14.9 \
        --column-bandwidth 'R(M=2.0)' 0.20 \
        --column-label 'Lambda(M=1.4)' '$\Lambda_{1.4}$' \
        --column-range 'Lambda(M=1.4)' 1.0 999.0 \
        --column-bandwidth 'Lambda(M=1.4)' 40 \
        --column-label 'Lambda(M=2.0)' '$\Lambda_{2.0}$' \
        --column-range 'Lambda(M=2.0)' 1.0 150.0 \
        --column-bandwidth 'Lambda(M=2.0)' 5 \
        --logcolumn 'pressurec2(baryon_density=5.6e+14)' \
        --column-label 'pressurec2(baryon_density=5.6e+14)' '$\log_{10}\left(p_{2.0}/c^2\ [\mathrm{g}/\mathrm{cm}^3]\right)$' \
        --column-range 'pressurec2(baryon_density=5.6e+14)' 12.9 14.2 \
        --column-bandwidth 'pressurec2(baryon_density=5.6e+14)' 0.10 \
        --column-multiplier "pressurec2(baryon_density=5.6e+14)" .43429\
        --logcolumn 'pressurec2(baryon_density=1.68e+15)' \
        --column-label 'pressurec2(baryon_density=1.68e+15)' '$\log_{10}\left(p_{6.0}/c^2\ [\mathrm{g}/\mathrm{cm}^3]\right)$' \
        --column-range 'pressurec2(baryon_density=1.68e+15)' 14.2 15.5 \
        --column-bandwidth 'pressurec2(baryon_density=1.68e+15)' 0.10 \
        --column-multiplier "pressurec2(baryon_density=1.68e+15)" .43429\
        -s "$IN1" "$SAMPS1" \
        -s "$OUT1" "$SAMPS1"\
        -s "$IN2" "$SAMPS2"\
        -s "$OUT2" "$SAMPS2"\
        $DEFAULT_WEIGHT_ARGS\
        $EXTRA_WEIGHT_ARGS\
        $COLOR_SCHEME\
        --output-dir $MAIN_DIR \
        --tag "$THIS_TAG" \
        --num-proc 8 \
        --num-points $NUM_POINTS \
        --level 0.9 \
        --legend \
        --grid \
        --rotate-xticklabels 90 \
        --figwidth 11.8 \
        --figheight 11.8 \
        --Verbose \
        --no-scatter \
        --Verbose 
        
done
