#!/usr/bin/bash

COUNT="$1"
TAGS="$2"
EOS_DIR_TAGS="$3"
EOS_CS2C2_DIR_TAGS="$4"
EOS_PER_DIR="$5"
WHICH_QUANTILES="$6"

bash "$WHICH_QUANTILES" "$COUNT" "$TAGS" "$EOS_DIR_TAGS" "$EOS_CS2C2_DIR_TAGS" "$EOS_PER_DIR"
